# Generated by Django 3.1.5 on 2021-02-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metar',
            name='plotHours',
            field=models.IntegerField(blank=True, help_text='Enter a number. Min = 12, Max = 96', null=True),
        ),
    ]
